name: Industrialisation continue sur le serveur AWS (Tomcat)
on: push
jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: |
          jar cvf Nom.war *
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ec2-35-180-181-139.eu-west-3.compute.amazonaws.com
        username: admin
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        source: "EmileALBERICI.war"
        target: "/opt/tomcat/webapps"
